name: Deploy to Render Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook For Hub
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_HUB }}
